#!/usr/bin/env python
import sys

if sys.hexversion <= 0x20707f0:
    from bzseeker import console

    if __name__ == '__main__':
        console.main()
else:
    print 'ERROR: bzseeker using python <= 2.7 version.'
    sys.exit(1)